# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.kernelParams = [
    "rootdelay=1"
    "usb-storage.quirks=0bda:9210:t" # Workaround for Realtek RTS9210 USB to SATA bridge freezing
  ];
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usbhid"
    "usb_storage"
    "uas"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/239faa95-300b-4697-a2b5-97324631b095";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/629E-0510";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077" # 777 - 077 = 700	rwx------	Only root can read, write, or execute.
    ];
  };

  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/c1258554-a703-4990-9747-ce5a9f8bbbed";
    fsType = "btrfs";
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
