{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.services.fr24feed; # A common convention for shorthand

  fr24keyValue =
    let
      key = if lib.isPath cfg.fr24key then builtins.readFile cfg.fr24key else cfg.fr24key;
    in
    lib.strings.trim key;

  iniFile = pkgs.writeText "fr24feed.ini" ''
    # Configuration generated by NixOS module
    receiver="avr-tcp"
    # The required key:
    fr24key="${fr24keyValue}"
    host="127.0.0.1:30002"
    bs="no"
    raw="no"
    logmode="1"
    logpath="/var/log/fr24feed"
    mlat="yes"
    mlat-without-gps="yes"
  '';

  fr24feed-fhs = pkgs.callPackage ./fr24feed-fhs.nix { };

  # The path to the executable wrapper script in the Nix store
  fr24feed-wrapper = "${fr24feed-fhs}/bin/fr24feed-fhs";

in
{
  # options.services.fr24feed.enable = lib.mkEnableOption "Flightradar24 Feeder service via nspawn";
  options.services.fr24feed = {
    enable = lib.mkEnableOption "Flightradar24 Feeder service via nspawn";

    fr24key = lib.mkOption {
      type =
        with lib.types;
        oneOf [
          str
          path
        ];
      default = "";
      description = ''
        The Flightradar24 Sharing Key (FR24KEY). Required for the service to run.
        Can be provided as a string directly, or as a path to a file containing the key.
      '';
      example = "A1B2C3D4E5F6G7H8";
    };

    # Add other configuration properties here, e.g.,
    # receiverOptions = mkOption { ... };
  };

  config = lib.mkIf cfg.enable {
    # Ensure the user has provided the required key before enabling the service
    # The 'check' attribute is useful for required options.
    assertions = [
      {
        assertion = fr24keyValue != "";
        message = "services.fr24feed.fr24key must be set and not be empty.";
      }
    ];

    # This creates a dedicated system user/group for the service
    users.users.fr24feed = {
      isSystemUser = true;
      group = "fr24feed";
    };
    users.groups.fr24feed = { };

    # Define the systemd service to run the container
    systemd.services.fr24feed = {
      description = "Flightradar24 Feeder FHS Wrapper";

      serviceConfig = {
        Type = "simple";
        Restart = "always";
        RestartSec = "5s";

        # Security: Run the service as the dedicated user
        User = "fr24feed";
        Group = "fr24feed";

        # Use the absolute path to the wrapper script.
        # Type=simple is fine because the wrapper script handles the long-running process.
        ExecStart = "${fr24feed-wrapper}";
        StandardOutput = "journal";
        StandardError = "journal";

        # Security: Harden the service (essential for services running outside a container)
        # Note: The FHS wrapper still runs processes inside a temporary namespace (bwrap).
        PrivateTmp = true;
        ProtectSystem = "strict";
        ProtectHome = true;
        NoNewPrivileges = true;
      };

      wantedBy = [ "multi-user.target" ];
    };

    # 5. Permissions for Bind-Mounted Directories (Host)
    systemd.tmpfiles.rules = [
      "d /var/log/fr24feed 0755 fr24feed fr24feed -"
    ];

    environment.etc."fr24feed.ini".source = iniFile;
  };
}
