{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.services.fr24feed; # A common convention for shorthand

  fr24feed-fhs = pkgs.callPackage ./fr24feed-fhs.nix {
    configHostPath = "/run/fr24feed/fr24feed.ini";
  };

  # The path to the executable wrapper script in the Nix store
  fr24feed-wrapper = "${fr24feed-fhs}/bin/fr24feed-fhs";

in
{
  # options.services.fr24feed.enable = lib.mkEnableOption "Flightradar24 Feeder service via nspawn";
  options.services.fr24feed = {
    enable = lib.mkEnableOption "Flightradar24 Feeder service via nspawn";

    fr24key = lib.mkOption {
      type =
        with lib.types;
        oneOf [
          str
          path
        ];
      default = "";
      description = ''
        The Flightradar24 Sharing Key (FR24KEY). Required for the service to run.
        Can be provided as a string directly, or as a path to a file containing the key.
      '';
      example = "A1B2C3D4E5F6G7H8";
    };

    # Add other configuration properties here, e.g.,
    # receiverOptions = mkOption { ... };
  };

  config = lib.mkIf cfg.enable {
    # Ensure the user has provided the required key before enabling the service
    # The 'check' attribute is useful for required options.
    assertions = [
      {
        assertion = cfg.fr24key != "";
        message = "services.fr24feed.fr24key must be set and not be empty.";
      }
    ];

    # This creates a dedicated system user/group for the service
    users.users.fr24feed = {
      isSystemUser = true;
      group = "fr24feed";
    };
    users.groups.fr24feed = { };

    # Define the systemd service to run the container
    systemd.services.fr24feed = {
      description = "Flightradar24 Feeder FHS Wrapper";

      # For secrets from sops-nix or agenix
      after = [
        "run-agenix.d.mount"
        "sops-nix.service"
      ];
      wants = [
        "run-agenix.d.mount"
        "sops-nix.service"
      ];

      # Create /run/fr24feed owned by the service user/group
      serviceConfig = {
        RuntimeDirectory = "fr24feed";

        Type = "simple";
        Restart = "always";
        RestartSec = "5s";

        # Security: Run the service as the dedicated user
        User = "fr24feed";
        Group = "fr24feed";

        # This script runs before ExecStart. The '+' allows it to run with privileges
        # necessary to write the config and set permissions before dropping to the service user.
        ExecStartPre =
          let
            generator = pkgs.writeShellScript "fr24-ini-generator" ''
              #!${pkgs.bash}/bin/bash
              set -eu

              FR24_KEY_INPUT="${cfg.fr24key}" # Value from Nix config

              # Check if the input is a file path and read from it,
              # otherwise use it as a literal key.
              if [[ -f "$FR24_KEY_INPUT" ]]; then
                KEY=$(cat "$FR24_KEY_INPUT")
              else
                KEY="$FR24_KEY_INPUT"
              fi

              # Write config to the RuntimeDirectory
              cat > /run/fr24feed/fr24feed.ini <<EOF
              # Configuration generated by NixOS module at runtime
              receiver="beast-tcp"
              fr24key=$(echo -n "$KEY" | tr -d '[:space:]')
              host="127.0.0.1:30005"
              bs="no"
              raw="no"
              logmode="1"
              logpath="/var/log/fr24feed"
              mlat="yes"
              mlat-without-gps="yes"
              EOF
            '';
          in
          # The '+' prefix runs the command with root privileges.
          "+${generator}";
        # Use the absolute path to the wrapper script.
        ExecStart = "${fr24feed-wrapper}";
        StandardOutput = "journal";
        StandardError = "journal";

        # Security: Harden the service (essential for services running outside a container)
        # Note: The FHS wrapper still runs processes inside a temporary namespace (bwrap).
        PrivateTmp = true;
        ProtectSystem = "strict";
        ProtectHome = true;
        NoNewPrivileges = true;
      };

      wantedBy = [ "multi-user.target" ];
    };

    # 5. Permissions for Bind-Mounted Directories (Host)
    systemd.tmpfiles.rules = [ "d /var/log/fr24feed 0755 fr24feed fr24feed -" ];

  };
}
